//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranMarioMario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCardIngredient
    {
        public int IdBarCardIngredient { get; set; }
        public int IdBarCard { get; set; }
        public int IdIngredient { get; set; }
    
        public virtual BarCard BarCard { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
