//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranMarioMario.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuIngredient = new HashSet<MenuIngredient>();
            this.OrderMenu = new HashSet<OrderMenu>();
        }
    
        public int IdMenu { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public decimal Sum { get; set; }
        public byte[] PhotoMenu { get; set; }
        public Nullable<int> Volume { get; set; }

        public string correctCategoryMenu
        {
            get
            {
                return CategoryMenu1.Name.ToString();
            }
        }
        public byte[] CorrectPhoto
        {
            get
            {
                if (PhotoMenu == null)
                    return File.ReadAllBytes("../../Resources/no.png");
                else return PhotoMenu;
            }
        }
        public byte[] CorrectPhotoСart
        {
            get
            {
                var menu = this.OrderMenu.FirstOrDefault()?.Menu1;
                if (menu != null)
                {
                    return menu.PhotoMenu;
                }
                else
                {
                    return File.ReadAllBytes("../../Resources/no.png");
                }
            }
        }

        public virtual CategoryMenu CategoryMenu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuIngredient> MenuIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenu> OrderMenu { get; set; }
    }
}
