//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranMarioMario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int IdOrderMenu { get; set; }
        public int MenuBarCard { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public string Modification { get; set; }
        public int OrderId { get; set; }
        public System.DateTime DateAdd { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
