//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranMarioMario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenuBarCard
    {
        public int IdOrderMenu { get; set; }
        public Nullable<int> NameMenu { get; set; }
        public Nullable<int> NameBarCard { get; set; }
        public int NumberOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual BarCard BarCard { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
